M48
; DRILL file {KiCad 9.0.4} date 2025-09-01T13:06:25+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-01T13:06:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X178.32Y-80.09
X178.32Y-85.87
T2
X144.365Y-74.515
X144.365Y-91.515
X182.0Y-75.0
X182.0Y-91.0
M30
